---
version: '3.5'

networks:
  arc-integration:
    name: arc-integration
    driver: bridge
    ipam:
     config:
       - subnet: 172.19.0.0/24  

services:
  sbt:
    container_name: sbt
    image: mozilla/sbt:8u212_1.2.8 
    networks:
      - arc-integration     
    command: tail -f /dev/null
    volumes:
      - ${PWD}:/app  
      - /tmp/pgp:/pgp
    working_dir: /app

  tensorflow_serving:
    image: tensorflow_serving/simple:latest
    networks:
      - arc-integration    
    build: tensorflow_serving/.

  postgres:
    image: postgres:10.4-alpine-init
    networks:
      - arc-integration    
    build: postgres/.
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: "SecretPass!2018"

  flask_serving:
    image: flask_serving/simple:latest
    networks:
      - arc-integration    
    build: flask_serving/.
  
  minio:
    image: minio/minio:it
    build: minio/.
    networks:
      - arc-integration    
    command: server /it
    environment:
      MINIO_ACCESS_KEY: AKIAIOSFODNN7EXAMPLE
      MINIO_SECRET_KEY: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
